config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users

 root :to => "home#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice:  'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:code, :description, :department, :brand, :aliquot, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
<div class ="row">
        <ul class="thumbnails">
    <a href="#" class="thumbnail">
    <img src="https://scontent-gru1-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/11665375_656407304460621_6639553809974595610_n.jpg?oh=323650f2b4e4ddfcbc7d28b11be602b3&oe=561E9248" alt="">
    </a>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CadastroOO</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
    </div>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Usuário <span class="caret"></span></a>
          <ul class="dropdown-menu">
           <% if user_signed_in? %>
      			Logged in as <strong><%= current_user.email %></strong><br>
      			<li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
      			<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
		<a href="/products/">Products</a>
    		<% else %>
     			<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> </li>
 <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>	
	<% end %>
          </ul>
        </li>
      </ul>
    </div>
</nav> 
<div class="container">
  <div class="row">
    <div class="col-xs-12"> 
      <p class="alert"><%= alert %></p>
      <%= yield %> 
    </div>
   </div>   
</div>


</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
   </div> 
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :aliquot %><br>
    <%= f.text_field :aliquot %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
	 
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing Products</h1>

<table class="table">
  <thead>
    <tr>
      <th>Code</th>
      <th>Description</th>
      <th>Department</th>
      <th>Brand</th>
      <th>Aliquot</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.code %></td>
        <td><%= product.description %></td>
        <td><%= product.department %></td>
        <td><%= product.brand %></td>
        <td><%= product.aliquot %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product, :class=>"btn btn-info "%></td>
        <td><%= link_to 'Edit', edit_product_path(product), :class=>"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } , :class=>"btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path,:class=>"btn btn-success" %></ %>

app/views/products/new.html.erb
<h1>Cadastre o novo produto</h1>
<%= render 'form' %>

	 
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @product.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Department:</strong>
  <%= @product.department %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>

<p>
  <strong>Aliquot:</strong>
  <%= @product.aliquot %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>